### ISSUE TITLE
HiFi.conf: can't stop mic from feeding into right speaker

### ISSUE THREAD

**Issue by plenaerts** [tallero/misc#1]
[HiFi.conf](https://github.com/tallero/misc/blob/master/HiFi.conf) switches my mic on all the time on the right speaker. Please suggest how we can try to control that from alsamixer or alternative.

Until we fix that I'm not including this file in the [arch linux aur package](https://aur.archlinux.org/packages/alsa-lib-x205ta/).

**Comment by tallero** [comment]
I used on a new installation and it worked as intended. Maybe do our asound.state differ?

`alsactl --file ~/.config/asound.state store`

Sure you can mute the microphone through `pavucontrol` if you use pulseaudio.

**Comment by plenaerts** [comment]
So I tried playing with a bit today and I don't see when my audio card decides to do what I set in pavucontrol.

At some boots the mic monitor to the right speaker is off. I can switch it on, but then I can't switch it off again in pavucontrol. A reboot after setting it to off does not switch it off either. It's not clear to me when the card switches off the monitoring to the right speaker.

Don't hesitate to ask me to try some stuff ;-) 

edit: I actually tried recording something and I don't get any input. I do get the monitor audio through with the trouble to switch it back off. I took [a small video to show](https://drive.google.com/open?id=1AUaLiQ6N5ks1FB_KaNn72AOT0-xxu4Hz). When my mouse stops moving I'm scratching the mic which is audible in the righ speaker, but not the vid.

**Comment by plenaerts** [comment]
Erm. [Your HiFi.conf](https://raw.githubusercontent.com/tallero/misc/master/HiFi.conf) is the same as in [the current PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=alsa-lib-x205ta). That is [this file at Pierre Bossarts repo](https://raw.githubusercontent.com/plbossart/UCM/c8b344ca650a62aa809242b0c9ba908eac963125/chtrt5645/HiFi.conf).

Am I missing something?

**Comment by tallero** [comment]
Sorry, apparently I uploaded the updated version only on Bossart's repo; as specified elsewhere, the file comes from harryharryharry in the X205TA ubuntu forums thread.
I'll correct it immediately.
In the meantime you can find it here:
https://raw.githubusercontent.com/tallero/UCM/3c98e1df0f076d05557cab2d719b13e5cfcba44a/sof-chtrt5645/HiFi.conf

**Comment by tallero** [comment]
Fix'd. Let me know if it works.

EDIT: pls vote for inclusion on bossart's repo
https://github.com/plbossart/UCM/pull/47

**Comment by plenaerts** [comment]
I don't get it.

[Your current HiFi.conf](https://raw.githubusercontent.com/tallero/misc/master/HiFi.conf) contains mail headers.

**Comment by plenaerts** [comment]
> In the meantime you can find it here: https://raw.githubusercontent.com/tallero/UCM/3c98e1df0f076d05557cab2d719b13e5cfcba44a/sof-chtrt5645/HiFi.conf

I tried this and I'm not getting any input devices. Again, that might be my lack of understanding of alsa and pulse, so please let me know if you want me to try anything.
![schermafdruk_2018-10-03_01-15-58](https://user-images.githubusercontent.com/14309550/46382147-e9dabf80-c6a9-11e8-84bc-89f844a898cc.png)

You can see I've selected "all input devices" and I get only the monitor...

**Comment by tallero** [comment]
Isn't that the deutsch for internal analog microphone? In the screenshot the mute button is pressed, try enabling it.

Il October 2, 2018 11:16:36 PM UTC, Pieter Lenaerts <notifications@github.com> ha scritto:
>> In the meantime you can find it here:
>https://raw.githubusercontent.com/tallero/UCM/3c98e1df0f076d05557cab2d719b13e5cfcba44a/sof-chtrt5645/HiFi.conf
>
>I tried this and I'm not getting any input devices. Again, that might
>be my lack of understanding of alsa and pulse, so please let me know if
>you want me to try anything.
>![schermafdruk_2018-10-03_01-15-58](https://user-images.githubusercontent.com/14309550/46382147-e9dabf80-c6a9-11e8-84bc-89f844a898cc.png)
>
>You can see I've selected "all input devices" and I get only the
>monitor...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tallero/misc/issues/1#issuecomment-426461581

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by plenaerts** [comment]
Muting and unmuting does nothing. This is a screenshot of the input devices and ports in the current aur package version. Note that only the monitor device remains with your HiFi.conf.
![schermafdruk_2018-10-04_22-03-57](https://user-images.githubusercontent.com/14309550/46499883-a73bf300-c821-11e8-84e2-943c0b2870c0.png)

**Comment by tallero** [comment]
Wait, what kernel are you on? Oh, right, you're using arch, so 4.18 I guess. I'll try rebooting with my HiFi.conf and upload also the alsa state file.

**Comment by tallero** [comment]
I've updated the repo with the good one. This is the last time, promised.

![schermata da 2018-10-06 00-03-24](https://user-images.githubusercontent.com/7817636/46562207-45e85280-c8fb-11e8-9c3a-c5cff8812084.png)

**Comment by plenaerts** [comment]
> Wait, what kernel are you on? Oh, right, you're using arch, so 4.18 I guess. I'll try rebooting with my HiFi.conf and upload also the alsa state file.

I am using [the kernel package that I maintain](https://aur.archlinux.org/packages/linux-x205ta/). This issue started out of an AUR comment you posted.

**Comment by tallero** [comment]
I'm really sorry. Anyway, I think now the issue could now be closed, the file from the actual commit MUST work, it comes from the laptop with the working mic directly.

Il October 6, 2018 6:06:20 AM UTC, Pieter Lenaerts <notifications@github.com> ha scritto:
>> Wait, what kernel are you on? Oh, right, you're using arch, so 4.18 I
>guess. I'll try rebooting with my HiFi.conf and upload also the alsa
>state file.
>
>I am [the kernel package that I
>maintain](https://aur.archlinux.org/packages/linux-x205ta/). This issue
>started out of an AUR comment you posted.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tallero/misc/issues/1#issuecomment-427549415

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by plenaerts** [comment]
Sorry, it doesn't work for me. If other people can test and confirm that it works then we can spend time trying to find out why it doesn't work for me.

Personnaly I'd keep this issue open for now to discuss this HiFi.conf file instead of the monster thread in the ubuntu forums. Up to you of course.

**Comment by tallero** [comment]
Sure you downloaded the last revision?

Il October 6, 2018 6:20:05 PM UTC, Pieter Lenaerts <notifications@github.com> ha scritto:
>Sorry, it doesn't work for me. If other people can test and confirm
>that it works then we can spend time trying to find out why it doesn't
>work for me.
>
>Personnaly I'd keep this issue open for now to discuss this HiFi.conf
>file instead of the monster thread in the ubuntu forums. Up to you of
>course.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tallero/misc/issues/1#issuecomment-427595642

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by plenaerts** [comment]
OK, I forgot to reboot. My mistake last night. I've got the mic working. I'll report this in your pull request to @plbossart.

This discussion should have taken place on your fork of Pierre's repo.
